- name: Compute | Nova nova.conf config file
  template:
    src: compute_files/etc/nova/nova.conf
    dest: /etc/nova/nova.conf
    owner: nova
    group: nova
    mode: 0640
    force: yes

- name: Compute | Neutron neutron.conf config file
  template:
    src: compute_files/etc/neutron/neutron.conf
    dest: /etc/neutron/neutron.conf
    owner: root
    group: neutron
    mode: 0644
    force: yes

- name: Compute | Neutron-Plugins-ML2 openvswitch_agent.ini file
  template:
    src: compute_files/etc/neutron/plugins/ml2/openvswitch_agent.ini
    dest: /etc/neutron/plugins/ml2/openvswitch_agent.ini
    owner: root
    group: neutron
    mode: 0644
    force: yes


- name: All Hosts | Network interfaces file
  template:
    src: compute_files/etc/network/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: 0644
    force: yes

- name: Compute | Nova nova-compute.conf config file
  template:
    src: compute_files/etc/nova/nova-compute.conf
    dest: /etc/nova/nova-compute.conf
    owner: nova
    group: nova
    mode: 0640
    force: yes